substitutions:
  devicename: bht002 
  upper_devicename: Hallway
  # location: Термостат MOES в ванной

external_components:
  - source:
      type: local
      path: my_components     
    components: [ tuya_termo ]
    refresh: 0s
  


esphome:
  name: $devicename
  friendly_name: ${upper_devicename} heater
  # on_boot:
  #   priority: 600
  #   then:
  #      - script.execute: script_show_text


esp8266:
  board: esp01_1m
  # board: esp12e
  # board: esp_wroom_02

# Enable logging
logger:
  level: INFO
  #level: VERBOSE
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret hallway_key

ota:
  - platform: esphome
    password: !secret hallway_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # ap:
  #   ssid: "Bht002 Fallback Hotspot"
  #   password: "UbOGEDIodJON"

captive_portal:
    
#последовательный порт
uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

time:
  - platform: sntp
    id: sync_time



climate:
  - platform: tuya_termo
    name: ${upper_devicename}
    uart_id: uart_bus # uart шина для управления MCU термостата
    time_id: sync_time # источник синхронизации времени
    time_sync_packets: false # пакеты синхронизациии времени, для некоторых версий устройств (по умолчанию false)
    optimistic: false 
    mode_restore: false # настройка восстановления режима работы после перезагрузки (по умолчанию true)
    # mcu_reset_pin: P9  # выходной пин принудительного сброса MCU термостата (только для доработанных термостатов)
    #   name: ${upper_devicename} MCU Reset Counter
    # mcu_reload_counter: # счетчик принудительных перезагрузок MCU термостата
    # reset_pin: P14 # входной пин для реинициализации протокола обмена с MCU, требуется для некоторых термостатов
    # status_pin: P15 # выходной пин индикации сетевого статуса, требуется для некоторых термостатов, но можно установить светодиод
    visual: # настройки для правильного отображения виджета, в большинстве случаев используются по умолчанию
      min_temperature: 5
      max_temperature: 35 
      eco_temperature: 20
      overheat_temperature: 45
      deadzone_temperature: 1
    internal_temperature: # сенсор температуры воздуха в помещении
      name: ${upper_devicename} Air Temp.  
    external_temperature: # внешний сенсор температуры пола
      name: ${upper_devicename} Floor Temp.
    children_lock:
      name: Child Lock
    shedule: # набор контролов для управления расписанием автономной работы термостата
      selector:
        name: Plan Day Selector
      hours:
        name: Plan Hours
      minutes:
        name: Plan Minutes
      temperature:
        name: Plan Temp.
    # product_id:   
    #   name: ${upper_devicename} Product Identifier
